## name: Lipgloss
## author: jarvis
## blurb: Charmbracelet Lipgloss-inspired theme with pink, purple, and cyan accents

foreground #EEEEEE
background #000000

cursor            #F25D94
cursor_text_color #000000

selection_foreground #EEEEEE
selection_background #874BFD

# ANSI colors
color0  #383838
color1  #FF5F87
color2  #73F59F
color3  #EDFF82
color4  #874BFD
color5  #A550DF
color6  #14F9D5
color7  #D9DCCF

# Bright colors
color8  #696969
color9  #F25D94
color10 #43BF6D
color11 #FFF7DB
color12 #7D56F4
color13 #d75fee
color14 #04B575
color15 #FFFDF5
