## name: Warp Dark
## author: jarvis
## blurb: WezTerm warp_dark theme ported to Kitty

foreground #ffffff
background #000000

cursor            #ffffff
cursor_text_color #000000

selection_foreground #ffffff
selection_background #616161

# ANSI colors
color0  #616161
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #66d9ef
color5  #ff79c6
color6  #8be9fd
color7  #f1f1f1

# Bright colors
color8  #8e8e8e
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #89ddff
color13 #ff92df
color14 #a4ffff
color15 #feffff
