# kitty.conf

# Font configuration
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
symbol_map U+1FBF0,U+1FBF1,U+1FBF2,U+1FBF3,U+1FBF4,U+1FBF5,U+1FBF6,U+1FBF7,U+1FBF8,U+1FBF9 Iosevka Nerd Font Mono
symbol_map U+26A1 FiraCode Nerd Font Mono
font_size        16.0

# Cursor configuration
cursor_shape            beam
cursor_beam_thickness   1
cursor_blink_interval   0.4 ease-in-out

# Colors
foreground       #BBC6F6
background       #1A1B28
cursor           #B2B2B2
cursor_text_color #292733

# Selection colors
selection_foreground #444257
selection_background #C4B5FF

# Scrollback settings
scrollback_lines 3000

# Window padding
window_padding_width 25

# Tab bar behavior (Kitty does not have a fancy tab bar like WezTerm)
hide_window_decorations titlebar-and-corners
# macos_titlebar_color background
# tab_bar_style top
macos_hide_from_tasks yes

# Color schemes (equivalent to the WezTerm's ANSI colors)
color0  #2A2734
color1  #E2514E
color2  #00BCDB
color3  #E1C381
color4  #5334B2
color5  #E69F51
color6  #2AB7E7
color7  #9B84EE

color8  #454159
color9  #E2514E
color10 #4EF4DF
color11 #E1C381
color12 #7B64C3
color13 #E69F51
color14 #24D5F8
color15 #EEEBFF

macos_quit_when_last_window_closed yes
confirm_os_window_close 0

# window jumping for tmux
map shift+cmd+] send_text all \x00n
map shift+cmd+[ send_text all \x00p
map cmd+t no_op
map cmd+w no_op
map cmd+1 no_op
map cmd+2 no_op
map cmd+3 no_op
map cmd+4 no_op
map cmd+5 no_op
map cmd+6 no_op
map cmd+7 no_op
map cmd+8 no_op
map cmd+9 no_op

# natural text edit
macos_option_as_alt yes
# Move to beginning/end of the line
map cmd+left  send_text all \x01
map cmd+right send_text all \x05

# Move by words
map option+left  send_text all \x1bb
map option+right send_text all \x1bf

# Delete previous/next word
map option+backspace  send_text all \x17
map option+delete     send_text all \x1bd

# undo
map cmd+z send_text all \x1f

# delete all previous/next words
map cmd+backspace send_text all \x15
map cmd+delete send_text all \x0b

# fullscreen
map cmd+enter toggle_maximized

# newline carry
map shift+enter send_text all \x20\\\n

# clipboard fix
# https://github.com/tmux/tmux/wiki/Clipboard#terminal-support---kitty
# clipboard_control write-primary write-clipboard no-append
