## name: Moonlight
## author: jarvis
## blurb: Dark blue background with muted Moonlight palette

foreground #BBC6F6
background #1A1B27

cursor            #B2B2B2
cursor_text_color #292733

selection_foreground #444257
selection_background #C4B5FF

# ANSI colors
color0  #2A2734
color1  #E2514E
color2  #00BCDB
color3  #E1C381
color4  #5334B2
color5  #E69F51
color6  #2AB7E7
color7  #9B84EE

# Bright colors
color8  #454159
color9  #E2514E
color10 #4EF4DF
color11 #E1C381
color12 #7B64C3
color13 #E69F51
color14 #24D5F8
color15 #EEEBFF
