[user]
name = "Adam Jarvis"
email = "ajarvis@ameba.ai"

[signing]
behavior = "drop"
backend = "gpg"
key = "E94E14177DD0EFD265FDABCEC6337B9F8FD4854B"

[git]
private-commits = "private"
sign-on-push = true

[remotes.origin]
auto-track-bookmarks = "glob:*"

[ui]
default-command = ["ls"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[snapshot]
auto-update-stale = true

[fsmonitor]
backend="watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true

[aliases]
weld = ["rebase", "--skip-emptied", "-s", "roots(mutable() & mine() & ::(mutable() & visible_heads() & mine()))", "-d", "main@origin"]
smelt = ["git", "push", "--revisions", "all() ~ conflicts()"]
fetch = ["git", "fetch"]
forge = ["util", "exec", "--", "sh", "-c", "jj fetch && jj weld && jj smelt"]
push = ["git", "push"]
pa = ["git", "push", "--all"]
ls = ["log", "-r", "@ | ancestors(trunk()..(mutable() & visible_heads() & mine()), 3) | trunk()"]
rm = ["abandon"]
# bc = ["bookmark", "create", "-r", "@", "concat(\"ajarvis/\", change_id.short())"]
bc = ["util", "exec", "--", "jj-bcn"]
spr = ["util", "exec", "--", "jj-spr"]

[template-aliases]
bookmark_prefix = "ajarvis/"
'format_short_id(id)' = 'id.shortest(6)'
'format_short_signature(signature)' = '''
label("author",
  if(signature.email() == "ajarvis@ameba.ai", "me",
  if(signature.email() == "craigsmassie@gmail.com", "craig",
  if(signature.email() == "craig@ameba.ai", "craig",
  signature.email().local()))))
'''
'format_timestamp(timestamp)' = 'timestamp.local().format("%Y-%m-%d %H:%M")'
'format_short_commit_header(commit)' = '''
separate(" ",
  format_short_change_id_with_change_offset(commit),
  format_short_signature(commit.author()),
  format_timestamp(commit_timestamp(commit)),
  commit.bookmarks(),
  commit.tags().filter(|x| !x.name().starts_with("release-main-")),
  commit.working_copies(),
  if(commit.contained_in('first_parent(@)'), label("git_head", "git_head()")),
  format_short_commit_id(commit.commit_id()),
  if(commit.conflict(), label("conflict", "conflict")),
)
'''

[revset-aliases]
private = "description(glob:'wip:*')"
recent = 'author_date(after:"7 days ago")'

[revsets]
immutable-heads = 'builtin_immutable_heads() | (trunk().. & ~mine()) | author_date(before:"2025-10-18")'
short-prefixes = "(trunk()..@):: | (trunk()..(mutable() & visible_heads() & mine()))"
log = "mine() | bookmarks() | ::trunk() | trunk().."
#short-prefixes = "mine() | @.. | bookmarks() | ::trunk() | trunk().."
