[user]
name = "Adam Jarvis"
email = "ajarvis@ameba.ai"

[signing]
behavior = "drop"
backend = "gpg"
key = "E94E14177DD0EFD265FDABCEC6337B9F8FD4854B"

[git]
private-commits = "private"
auto-local-bookmark = true
sign-on-push = true

[ui]
default-command = ["diff", "-s"]
#diff.tool = "bat"

[aliases]
yank = ["rebase", "--skip-emptied", "-s", "all:roots(mutable() & mine())", "-d", "trunk()"]
forge = ["git", "push", "-r", "all:roots(mutable() & mine() & ~private & ~conflicts())"]
fetch = ["git", "fetch"]
push = ["git", "push", "--allow-new"]
pa = ["git", "push", "--all"]
ls = ["log", "-r", "@ | ancestors(trunk()..(mutable() & visible_heads() & mine()), 3) | trunk()"]
rm = ["abandon"]
bc = ["bookmark", "create", "-r", "@", "concat(\"ajarvis/\", change_id.short())"]
bcn = ["bookmark", "create", "r", "@"]

[template-aliases]
bookmark_prefix = "ajarvis/"

[revset-aliases]
immutable_heads = "builtin_immutable_heads() | (trunk().. & ~mine())"
private = "description(glob:'wip:*')"
