# Tab bar
tab_bar_edge   bottom
tab_bar_style  custom
tab_bar_min_tabs 1

active_tab_foreground   #ffffff
active_tab_background   #3e68d7
active_tab_font_style   bold
inactive_tab_foreground #828bb8
inactive_tab_background #1e2030
inactive_tab_font_style normal

# Use 'none' to inherit from the active theme's background color
tab_bar_background      none
tab_bar_margin_color    none
