# Advanced settings
scrollback_lines 50000

allow_remote_control yes
listen_on unix:/tmp/kitty

shell_integration no-url no-cursor

# Don't update window title from shell
dynamic_background_opacity no

# Bell
enable_audio_bell no
visual_bell_duration 0

# URL handling
url_style curly
detect_urls no

# Clipboard
clipboard_control write-clipboard write-primary read-clipboard
